# Generated by Django 3.1.6 on 2021-02-05 13:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210205_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 14, 20, 59, 59410)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 14, 20, 59, 59410)),
        ),
    ]
