# Generated by Django 3.1.6 on 2021-02-08 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210205_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 9, 3, 18, 961071)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 9, 3, 18, 962072)),
        ),
    ]
